services:
  react:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - express
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules

  express:
    container_name: express
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
